version: '3.1'

services:
  database:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: ordena
      POSTGRES_PASSWORD: root
